const characters = ["aback",
"abaft",
"abandoned",
"abashed",
"aberrant",
 "abhorrent",
 "abiding",
 "abject",
 "ablaze",
 "able",
 "abnormal",
 "aboard",
 "aboriginal",
 "abortive",
 "abounding",
 "abrasive",
 "abrupt",
 "absent",
 "absorbed",
 "absorbing",
 "abstracted",
 "absurd",
 "abundant",
 "abusive",
 "accept",
 "acceptable",
 "accessible",
 "accidental",
 "account",
 "accurate",
 "achiever",
 "acid",
 "acidic",
 "acoustic",
 "acoustics",
 "acrid",
 "act",
 "action",
 "activity",
 "actor",
 "actually",
 "ad hoc",
 "adamant",
 "adaptable",
 "add",
 "addicted",
 "addition",
 "adhesive",
 "adjoining",
 "adjustment",
 "admire",
 "admit",
 "adorable",
 "adventurous",
 "advertisement",
 "advice",
 "advise",
 "afford",
 "afraid",
 "aftermath",
 "afternoon",
 "afterthought",
 "aggressive",
 "agonizing",
 "agree",
 "agreeable",
 "agreement",
 "ahead",
 "air",
 "airplane",
 "airport",
 "ajar",
 "alarm",
 "alcoholic",
 "alert",
 "alike",
 "alive",
 "alleged",
 "allow",
 "alluring",
 "aloof",
 "amazing",
 "ambiguous",
 "ambitious",
 "amount",
 "amuck",
 "amuse",
 "amused",
 "amusement",
 "amusing",
 "analyse",
 "ancient",
 "anger",
 "angle",
 "angry",
 "animal",
 "animated",
"announce",
"annoy",
"annoyed"];

export const COLUMNS = [
    {
        label: 'ID',
        key: 'id',
        type: 'text',
        hidden: true,
        defaultValue: '',
        sort: true,
    },
    {
        label: 'Request Name',
        key: 'RequestName',
        type: 'text',
        required: 'required',
        defaultValue: '',
        max: 255,
        sort: true,
    },
    {
        label: 'Requestor',
        key: 'Requestor',
        type: 'select',
        reference: 'Users',
        displayValue: 'DisplayName',
        required: 'required',
        defaultValue: ''
    },
    {
        label: 'Good Ending',
        key: 'GoodEnding',
        type: 'radio',
        options: ['Yes', 'Depends', 'No'],
        required: 'required',
        defaultValue: ''
    },
    {
        label: 'Deadline',
        key: 'Deadline',
        type: 'date',
        required: 'required',
        defaultValue: new Date(new Date().setDate(new Date().getDate() + 28)),
        min: new Date(new Date().setDate(new Date().getDate() + 28)),
        sort: true

    },
    {
        label: 'Need Storyteller',
        key: 'NeedStoryteller',
        type: 'checkbox',
        defaultValue: false,
        required: 'required'
    },
    {
        label: 'Storyteller',
        key: 'Storyteller',
        type: 'select',
        reference: 'Users',
        displayValue: 'DisplayName',
        visibleDependent: 'NeedStoryteller',
        mandatoryDependent: 'NeedStoryteller',
        defaultValue: ''
    },
    {
        label: 'Budget',
        key: 'Budget',
        type: 'numeric',
        min: 250000,
        description: 'In FBL Dollars',
        defaultValue: '',
        sort: true
    },
    {
        label: 'Status',
        key: 'Status',
        type: 'text',
        hidden: true,
        defaultValue: 'Draft',
        sort: true
    },
    {
        label: 'Description',
        key: 'Description',
        type: 'textarea',
        required: 'required',
        defaultValue: '',
        min: 250,
        description: 'No spoilers please',
        width: 2,
    },
    {
        label: 'Desired characters',
        key: 'WantedCharacters',
        type: 'multichoice',
        options: characters,
        
        defaultValue: [],
        width: 2,
    }, 
    {
        label: 'Actions',
        type: 'action',
        button: {
            label: 'Open →',
            action: 'redirect',
            url: '/form.html?id='
        }
    }
];

export const BASIC_URL = 'http://localhost:3000';

